import type { Metadata } from "next";
import { Inter, Nunito_Sans } from "next/font/google";
import "./globals.css";
import Notification from "@/components/notification/Notification";
import QueryProviders from '@/providers/QueryProvider';

// Cấu hình Font chữ Inter chuẩn hỗ trợ tiếng Việt mượt mà
const nunitoSans = Nunito_Sans({                    
    subsets: ["latin", "vietnamese"],               
    weight: ["400", "500", "600", "700", "800"],
    variable: "--font-nunito-sans",                 
    display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={nunitoSans.variable}>
      <body className="font-sans antialiased bg-gray-50 text-gray-900">
        <QueryProviders>
            {children}
          <Notification/>
        </QueryProviders>
      </body>
    </html>
  );
}
